name: chat_example
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_lints: ^2.0.3
  provider: ^6.0.5
  dio: ^5.3.3
  go_router: ^12.0.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  freezed: ^2.4.3
  copy_with_extension_gen: ^5.0.4
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  retrofit: ^4.0.2
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.1
  image_picker: ^1.0.4
  copy_with_extension: ^5.0.4
  fresh_dio: ^0.4.1
  firebase_core: ^2.20.0
  firebase_auth: ^4.12.0
  firebase_storage: ^11.4.0
  firebase_database: ^10.3.2
  cloud_firestore: ^4.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  build_runner: ^2.4.6
  go_router_builder: ^2.3.4
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.0
  flutter_gen_runner: ^5.3.2

dependency_overrides:

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/

flutter_gen:
  assets:
    outputs:
      class_name: Assets
      style: camel-case
  integrations:
    flutter_svg: true
