// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsaBj03S6X0i3Y3TA9Z__l9lnibgT5qTw',
    appId: '1:1040303093355:android:10a15baed227aa4a0aa32e',
    messagingSenderId: '1040303093355',
    projectId: 'chat-example-d8c48',
    databaseURL: 'https://chat-example-d8c48-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-example-d8c48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmE_4plNHzV4UD2CyAx_EUI9GdsdTKSQY',
    appId: '1:1040303093355:ios:2f3b2e298d961c950aa32e',
    messagingSenderId: '1040303093355',
    projectId: 'chat-example-d8c48',
    databaseURL: 'https://chat-example-d8c48-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-example-d8c48.appspot.com',
    iosBundleId: 'com.example.chatExample',
  );
}
